import React from "react";

export const PromoterListData = [
    {
        promoter_id: 'pro-00-00-01',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-02',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-03',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-04',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-05',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-06',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-07',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-08',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-09',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-10',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-11',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
    {
        promoter_id: 'pro-00-00-12',
        edu_level: 'Advanced Level',
        age_level: '13 - 15',
        region: 'North West',
        language: 'Sinhala',
        gender:'Male',
    },
]